name: techniques
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - bokeh=2.2.3
  - pip
  - dask=2021.2.0
  - distributed=2021.2.0
  - dask-ml=1.8.0
  - dask_labextension
  - pip:
    - gym
    - ray[default]
    - ray[rllib]
    - tensorflow
    - pyspark
    - mlflow

