name: techniques
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - bokeh=2.2.3
  - pip
  - dask=2021.2.0
  - distributed=2021.2.0
  - dask-ml=1.8.0
  - dask_labextension=5.0.0
  - nodejs
  - aioredis=1.3.1
  - pip:
    - gym==0.18.0
    - ray[rllib]==1.2.0
    - tensorflow==2.4.1
    - pyspark
    - mlflow

