name: techniques
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - pip
  - dask=2021.8.1
  - dask-ml
  - nodejs
  - dask_labextension
  - pip:
    - gym
    - ray[default]
    - ray[rllib]
    - tensorflow
    - pyspark
    - mlflow

