name: techniques
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - bokeh=2.2.3
  - pip
  - dask=2021.2.0
  - distributed=2021.2.0
  - dask-ml=1.8.0
  - dask_labextension=5.0.0
  - nodejs
  - pip:
    - gym
    - ray[rllib]==1.4.1
    - tensorflow==2.5.0
    - pyspark
    - mlflow

