#!/bin/bash

jupyter labextension install --minimize=False --clean \
    dask-labextension \
    @jupyter-widgets/jupyterlab-manager

#Download Apache Spark
wget https://www-eu.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
tar -xzf spark-2.4.4-bin-hadoop2.7.tgz

#Tidy up
rm spark-2.4.4-bin-hadoop2.7.tgz

SPARK_HOME=$HOME/spark-2.4.4-bin-hadoop2.7

jupyter toree install --user --spark_home=$SPARK_HOME

#Jupyter server proxy
jupyter serverextension enable --sys-prefix jupyter_server_proxy